# Generated by Django 4.1 on 2022-08-26 02:01

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Familiar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('parentesco', models.CharField(max_length=50)),
                ('dni', models.IntegerField()),
                ('nacimiento', models.DateField(blank=True, default=datetime.date(2022, 8, 25), null=True)),
            ],
        ),
    ]
